version: '3'

services:

  client:
    image: muzam1l/mooz
    ports:
      - 9001:80
   # environment:
     # - REACT_APP_SOCKET_URL=https://agilityportal.co:5000/

  server:
    image: muzam1l/mooz-server
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      #- ALLOW_ORIGIN=agilityportal.co
